server:
  port: 8080

spring:
  application:
    name: external-observer
  data:
    mongodb:
      uri: mongodb://localhost:27017/external-observer
      auto-index-creation: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.externalobserver: DEBUG
    org.springframework.data.mongodb: INFO
    org.springframework.security: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.externalobserver.controller
  paths-to-match: /api/** 